/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	submarinerv1alpha1 "github.com/mkimuram/k8s-ext-connector/pkg/apis/submariner/v1alpha1"
	versioned "github.com/mkimuram/k8s-ext-connector/pkg/client/clientset/versioned"
	internalinterfaces "github.com/mkimuram/k8s-ext-connector/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/mkimuram/k8s-ext-connector/pkg/client/listers/submariner/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ForwarderInformer provides access to a shared informer and lister for
// Forwarders.
type ForwarderInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ForwarderLister
}

type forwarderInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewForwarderInformer constructs a new informer for Forwarder type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewForwarderInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredForwarderInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredForwarderInformer constructs a new informer for Forwarder type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredForwarderInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SubmarinerV1alpha1().Forwarders(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SubmarinerV1alpha1().Forwarders(namespace).Watch(options)
			},
		},
		&submarinerv1alpha1.Forwarder{},
		resyncPeriod,
		indexers,
	)
}

func (f *forwarderInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredForwarderInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *forwarderInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&submarinerv1alpha1.Forwarder{}, f.defaultInformer)
}

func (f *forwarderInformer) Lister() v1alpha1.ForwarderLister {
	return v1alpha1.NewForwarderLister(f.Informer().GetIndexer())
}
