apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: forwarders.submariner.io
spec:
  group: submariner.io
  names:
    kind: Forwarder
    listKind: ForwarderList
    plural: forwarders
    singular: forwarder
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Forwarder is the Schema for the forwarders API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ForwarderSpec defines the desired state of Forwarder
          type: object
        status:
          description: ForwarderStatus defines the observed state of Forwarder
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
