apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ext-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-ext-connector
  template:
    metadata:
      labels:
        name: k8s-ext-connector
    spec:
      serviceAccountName: k8s-ext-connector
      containers:
        - name: k8s-ext-connector
          # Replace this with the built image name
          image: k8s-ext-connector:v0.0.1
          command:
          - k8s-ext-connector
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "k8s-ext-connector"
