kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-ext-connector
subjects:
- kind: ServiceAccount
  name: k8s-ext-connector
  namespace: external-services
roleRef:
  kind: ClusterRole
  name: k8s-ext-connector
  apiGroup: rbac.authorization.k8s.io
