/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/mkimuram/k8s-ext-connector/pkg/apis/submariner/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeForwarders implements ForwarderInterface
type FakeForwarders struct {
	Fake *FakeSubmarinerV1alpha1
	ns   string
}

var forwardersResource = schema.GroupVersionResource{Group: "submariner.io", Version: "v1alpha1", Resource: "forwarders"}

var forwardersKind = schema.GroupVersionKind{Group: "submariner.io", Version: "v1alpha1", Kind: "Forwarder"}

// Get takes name of the forwarder, and returns the corresponding forwarder object, and an error if there is any.
func (c *FakeForwarders) Get(name string, options v1.GetOptions) (result *v1alpha1.Forwarder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(forwardersResource, c.ns, name), &v1alpha1.Forwarder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Forwarder), err
}

// List takes label and field selectors, and returns the list of Forwarders that match those selectors.
func (c *FakeForwarders) List(opts v1.ListOptions) (result *v1alpha1.ForwarderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(forwardersResource, forwardersKind, c.ns, opts), &v1alpha1.ForwarderList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ForwarderList{ListMeta: obj.(*v1alpha1.ForwarderList).ListMeta}
	for _, item := range obj.(*v1alpha1.ForwarderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested forwarders.
func (c *FakeForwarders) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(forwardersResource, c.ns, opts))

}

// Create takes the representation of a forwarder and creates it.  Returns the server's representation of the forwarder, and an error, if there is any.
func (c *FakeForwarders) Create(forwarder *v1alpha1.Forwarder) (result *v1alpha1.Forwarder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(forwardersResource, c.ns, forwarder), &v1alpha1.Forwarder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Forwarder), err
}

// Update takes the representation of a forwarder and updates it. Returns the server's representation of the forwarder, and an error, if there is any.
func (c *FakeForwarders) Update(forwarder *v1alpha1.Forwarder) (result *v1alpha1.Forwarder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(forwardersResource, c.ns, forwarder), &v1alpha1.Forwarder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Forwarder), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeForwarders) UpdateStatus(forwarder *v1alpha1.Forwarder) (*v1alpha1.Forwarder, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(forwardersResource, "status", c.ns, forwarder), &v1alpha1.Forwarder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Forwarder), err
}

// Delete takes name of the forwarder and deletes it. Returns an error if one occurs.
func (c *FakeForwarders) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(forwardersResource, c.ns, name), &v1alpha1.Forwarder{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeForwarders) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(forwardersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ForwarderList{})
	return err
}

// Patch applies the patch and returns the patched forwarder.
func (c *FakeForwarders) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Forwarder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(forwardersResource, c.ns, name, pt, data, subresources...), &v1alpha1.Forwarder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Forwarder), err
}
