/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/mkimuram/k8s-ext-connector/pkg/apis/submariner/v1alpha1"
	scheme "github.com/mkimuram/k8s-ext-connector/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ForwardersGetter has a method to return a ForwarderInterface.
// A group's client should implement this interface.
type ForwardersGetter interface {
	Forwarders(namespace string) ForwarderInterface
}

// ForwarderInterface has methods to work with Forwarder resources.
type ForwarderInterface interface {
	Create(*v1alpha1.Forwarder) (*v1alpha1.Forwarder, error)
	Update(*v1alpha1.Forwarder) (*v1alpha1.Forwarder, error)
	UpdateStatus(*v1alpha1.Forwarder) (*v1alpha1.Forwarder, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Forwarder, error)
	List(opts v1.ListOptions) (*v1alpha1.ForwarderList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Forwarder, err error)
	ForwarderExpansion
}

// forwarders implements ForwarderInterface
type forwarders struct {
	client rest.Interface
	ns     string
}

// newForwarders returns a Forwarders
func newForwarders(c *SubmarinerV1alpha1Client, namespace string) *forwarders {
	return &forwarders{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the forwarder, and returns the corresponding forwarder object, and an error if there is any.
func (c *forwarders) Get(name string, options v1.GetOptions) (result *v1alpha1.Forwarder, err error) {
	result = &v1alpha1.Forwarder{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("forwarders").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Forwarders that match those selectors.
func (c *forwarders) List(opts v1.ListOptions) (result *v1alpha1.ForwarderList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ForwarderList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("forwarders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested forwarders.
func (c *forwarders) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("forwarders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a forwarder and creates it.  Returns the server's representation of the forwarder, and an error, if there is any.
func (c *forwarders) Create(forwarder *v1alpha1.Forwarder) (result *v1alpha1.Forwarder, err error) {
	result = &v1alpha1.Forwarder{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("forwarders").
		Body(forwarder).
		Do().
		Into(result)
	return
}

// Update takes the representation of a forwarder and updates it. Returns the server's representation of the forwarder, and an error, if there is any.
func (c *forwarders) Update(forwarder *v1alpha1.Forwarder) (result *v1alpha1.Forwarder, err error) {
	result = &v1alpha1.Forwarder{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("forwarders").
		Name(forwarder.Name).
		Body(forwarder).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *forwarders) UpdateStatus(forwarder *v1alpha1.Forwarder) (result *v1alpha1.Forwarder, err error) {
	result = &v1alpha1.Forwarder{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("forwarders").
		Name(forwarder.Name).
		SubResource("status").
		Body(forwarder).
		Do().
		Into(result)
	return
}

// Delete takes name of the forwarder and deletes it. Returns an error if one occurs.
func (c *forwarders) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("forwarders").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *forwarders) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("forwarders").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched forwarder.
func (c *forwarders) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Forwarder, err error) {
	result = &v1alpha1.Forwarder{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("forwarders").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
